version: '3.0'

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    networks:
      - daap

  dynamo-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    networks:
      - daap
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local

networks:
  daap: {}
